show_plots: true
lc_send_delay_s: 15
vlc_frame_period_s: 0.5
robot_id: 0
config_path: $(find ouroboros_ros)/config/vlc_server_config.yaml

fixed_frame: world
hint_body_frame: ground_truth/husky/base

body_frame: husky/base
camera_frame: husky/camera
