place_method:
  type: Salad
  embedding_size: 8448
  model_source: torchhub
  model_variant: serizba/salad
  weight_source: dinov2_salad
keypoint_method:
  type: SuperPoint
  max_keypoints: 1024
descriptor_method: null
match_method:
  type: Lightglue
  feature_type: superpoint
pose_method:
  type: ground_truth

lc_frame_lockout_s: 10
place_match_threshold: 0.55
strict_keypoint_evaluation: false

display_method:
    type: ros
    display_place_matches: True
    display_keypoint_matches: True
