[build-system]
requires = ["setuptools", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest]
testpaths = "tests"
addopts = ["--cov-report=term-missing"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
