name: Ouroboros CI
run-name: Ouroboros CI
on:
    push:
        branches: main
    pull_request:
        branches:
            - main
            - develop
jobs:
  Ouroboros-CI:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.8", "3.13"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            path: ouroboros_repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-commit
        run: pip install pre-commit && cd ${{ github.workspace }}/ouroboros_repo && pre-commit run --all-files
      - name: Dependencies
        run: sudo apt install libeigen3-dev
      - name: Install Ouroboros
        run: cd ${{ github.workspace }}/ouroboros_repo && pwd && pip install .
      - name: Run test script
        run: cd ${{ github.workspace }}/ouroboros_repo && pytest
      - run: echo "🍏 This job's status is ${{ job.status }}."
