name: Ouroboros-ROS-CI
run-name: Ouroboros-ROS-CI
on:
    push:
        branches: main
    pull_request:
        branches:
            - main
            - develop
            - ros2
jobs:
  Ouroboros-ROS-CI:
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - name: Update git
        run: sudo apt update && sudo apt install -y git
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            path: src/ouroboros_repo
            submodules: recursive
      - name: Dependencies
        run: |
            sudo apt install -y python3-colcon-common-extensions python3-pip ros-jazzy-cv-bridge libeigen3-dev
      - name: Install Ouroboros
        run: pwd && ls && cd src/ouroboros_repo && pwd && pip install ./ouroboros
      - name: Install ROS packages with rosdep
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -s  # do a dry-run first
          rosdep install --from-paths src --ignore-src -r -y
      - name: colcon build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --continue-on-error
      - name: Run test script
        shell: bash
        run: |
          source install/setup.bash
          cd src/ouroboros_repo
          pytest ouroboros_ros/tests
      - run: echo "🍏 This job's status is ${{ job.status }}."
